// Family data - you can modify this to match your actual family data
const familyData = [
  // Generation 1 - Family Heads
  {
    id: "1",
    name: "A T Mohamedunny",
    profession: "",
    qualification: "",
    contact: "",
    isHead: true,
    generation: 1,
    parentId: null,
    spouse: "P.M Kochu Rabiya",
    children: ["2", "3", "4"],
    branch: "A T Mohamedunny & P.M Kochu Rabiya",
    isDeceased: true,
  },
  {
    id: "1-spouse",
    name: "P.M Kochu Rabiya",
    profession: "",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 1,
    parentId: null,
    spouse: "A T Mohamedunny",
    children: ["2", "3", "4"],
    branch: "A T Mohamedunny & P.M Kochu Rabiya",
    isDeceased: false,
  },

  // Generation 2
  {
    id: "2",
    name: "Kunjupathumma",
    profession: "",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 2,
    parentId: "1",
    spouse: "",
    children: ["5", "6"],
    branch: "Kunjupathumma",
    isDeceased: false,
  },
  {
    id: "3",
    name: "Pathavu",
    profession: "",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 2,
    parentId: "1",
    spouse: "",
    children: ["7"],
    branch: "Pathavu",
    isDeceased: false,
  },
  {
    id: "4",
    name: "Nafeesakutty",
    profession: "",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 2,
    parentId: "1",
    spouse: "",
    children: ["8", "9"],
    branch: "Nafeesakutty",
    isDeceased: false,
  },

  // Generation 3
  {
    id: "5",
    name: "Alikunji",
    profession: "Business",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 3,
    parentId: "2",
    spouse: "",
    children: ["10"],
    branch: "Alikunji",
    isDeceased: false,
  },
  {
    id: "6",
    name: "Kunjaisu",
    profession: "",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 3,
    parentId: "2",
    spouse: "",
    children: ["11"],
    branch: "Kunjaisu",
    isDeceased: false,
  },
  {
    id: "7",
    name: "Aminakutty",
    profession: "",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 3,
    parentId: "3",
    spouse: "",
    children: ["12"],
    branch: "Aminakutty",
    isDeceased: false,
  },
  {
    id: "8",
    name: "Aboobacker",
    profession: "",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 3,
    parentId: "4",
    spouse: "",
    children: ["13"],
    branch: "Aboobacker",
    isDeceased: false,
  },
  {
    id: "9",
    name: "Zainba",
    profession: "",
    qualification: "",
    contact: "",
    isHead: false,
    generation: 3,
    parentId: "4",
    spouse: "",
    children: ["14"],
    branch: "Zainba",
    isDeceased: false,
  },

  // Generation 4 - Sample children
  {
    id: "10",
    name: "Mohammed Ali",
    profession: "Engineer",
    qualification: "B.Tech",
    contact: "+91 9876543210",
    isHead: false,
    generation: 4,
    parentId: "5",
    spouse: "Fatima",
    children: [],
    branch: "Alikunji",
    isDeceased: false,
  },
  {
    id: "11",
    name: "Abdul Rahman",
    profession: "Doctor",
    qualification: "MBBS",
    contact: "+91 9876543211",
    isHead: false,
    generation: 4,
    parentId: "6",
    spouse: "",
    children: [],
    branch: "Kunjaisu",
    isDeceased: false,
  },
  {
    id: "12",
    name: "Rasheed",
    profession: "Teacher",
    qualification: "M.A",
    contact: "+91 9876543212",
    isHead: false,
    generation: 4,
    parentId: "7",
    spouse: "Khadija",
    children: [],
    branch: "Aminakutty",
    isDeceased: false,
  },
  {
    id: "13",
    name: "Ibrahim",
    profession: "Business",
    qualification: "B.Com",
    contact: "+91 9876543213",
    isHead: false,
    generation: 4,
    parentId: "8",
    spouse: "",
    children: [],
    branch: "Aboobacker",
    isDeceased: false,
  },
  {
    id: "14",
    name: "Mariam",
    profession: "Nurse",
    qualification: "B.Sc Nursing",
    contact: "+91 9876543214",
    isHead: false,
    generation: 4,
    parentId: "9",
    spouse: "Yusuf",
    children: [],
    branch: "Zainba",
    isDeceased: false,
  },
]
