// Complete Family Data - All 10 Families with Every Member
const familyData = [
  // Family 1: A T Mohamedunny & P.M Kochu Rabiya - COMPLETE
  {
    id: "head-1",
    name: "A T Mohamedunny",
    isHead: true,
    generation: 1,
    spouse: "P.M Kochu Rabiya",
    children: ["najuma", "nazir", "naseema", "najeeba"],
    branch: "A T Mohamedunny & P.M Kochu Rabiya",
    isDeceased: true,
  },
  {
    id: "head-1-spouse",
    name: "P.M Kochu Rabiya",
    isHead: false,
    generation: 1,
    spouse: "A T Mohamedunny",
    children: ["najuma", "nazir", "naseema", "najeeba"],
    branch: "A T Mohamedunny & P.M Kochu Rabiya",
  },
  {
    id: "najuma",
    name: "Najuma PM",
    profession: "Retired Head Mistress",
    qualification: "BSc, B.Ed",
    contact: "0091 9497824025",
    isHead: false,
    generation: 2,
    parentId: "head-1",
    spouse: "Dr CV Abdulla Kutty",
    children: ["afdal", "aysha-nasrene", "aslam"],
    branch: "Najuma PM & Dr CV Abdulla Kutty",
  },
  {
    id: "najuma-spouse",
    name: "Dr CV Abdulla Kutty",
    profession: "Retired Principal",
    qualification: "MA, PhD",
    contact: "0091 9447944198",
    isHead: false,
    generation: 2,
    parentId: "head-1",
    spouse: "Najuma PM",
    children: ["afdal", "aysha-nasrene", "aslam"],
    branch: "Najuma PM & Dr CV Abdulla Kutty",
  },
  {
    id: "nazir",
    name: "PM Nazir",
    profession: "Business",
    qualification: "B.A",
    contact: "00971 55 9484721",
    isHead: false,
    generation: 2,
    parentId: "head-1",
    spouse: "Shainas Alamana Mohamed Haneefa",
    children: ["abbas-nazir", "aysha-nazir"],
    branch: "PM Nazir & Shainas Alamana",
  },
  {
    id: "nazir-spouse",
    name: "Shainas Alamana Mohamed Haneefa",
    profession: "Homemaker",
    qualification: "B.A",
    contact: "00971 54 4890592",
    isHead: false,
    generation: 2,
    parentId: "head-1",
    spouse: "PM Nazir",
    children: ["abbas-nazir", "aysha-nazir"],
    branch: "PM Nazir & Shainas Alamana",
  },
  {
    id: "naseema",
    name: "Naseema P.M.",
    profession: "Homemaker",
    qualification: "Pre-degree, Diploma in Home Sciences",
    contact: "0091 9746799307",
    isHead: false,
    generation: 2,
    parentId: "head-1",
    spouse: "Abdul Majeed N.P",
    children: ["adeeb", "farhana", "adheela"],
    branch: "Naseema P. M & Abdul Majeed N.P",
  },
  {
    id: "naseema-spouse",
    name: "Abdul Majeed N.P",
    isHead: false,
    generation: 2,
    parentId: "head-1",
    spouse: "Naseema P.M.",
    children: ["adeeb", "farhana", "adheela"],
    branch: "Naseema P. M & Abdul Majeed N.P",
  },
  {
    id: "najeeba",
    name: "Najeeba PM",
    profession: "Homemaker",
    qualification: "B.A",
    contact: "0091 9946955299",
    isHead: false,
    generation: 2,
    parentId: "head-1",
    spouse: "Mohammed Salim K.H",
    children: ["salman", "shehzad", "zaahir"],
    branch: "Najeeba PM & Mohammed Salim K.H",
  },
  {
    id: "najeeba-spouse",
    name: "Mohammed Salim K.H",
    profession: "Retired Head Master",
    qualification: "MSc, B.Ed",
    contact: "0091 9447920072",
    isHead: false,
    generation: 2,
    parentId: "head-1",
    spouse: "Najeeba PM",
    children: ["salman", "shehzad", "zaahir"],
    branch: "Najeeba PM & Mohammed Salim K.H",
  },
  {
    id: "afdal",
    name: "Afdal Abdulla",
    profession: "Information Security Officer",
    qualification: "BE",
    contact: "00974 70002766",
    isHead: false,
    generation: 3,
    parentId: "najuma",
    spouse: "Thameema Sharaf",
    children: ["zayan", "razan"],
    branch: "Najuma PM & Dr CV Abdulla Kutty",
  },
  {
    id: "thameema",
    name: "Thameema Sharaf",
    profession: "Textile Designer",
    qualification: "BDes",
    contact: "00974 50750432",
    isHead: false,
    generation: 3,
    parentId: "najuma",
    spouse: "Afdal Abdulla",
    children: ["zayan", "razan"],
    branch: "Najuma PM & Dr CV Abdulla Kutty",
  },
  {
    id: "aysha-nasrene",
    name: "Adv. Aysha Nasrene",
    profession: "Lawyer (Practising)",
    qualification: "BSc, MA, LLB",
    contact: "0091 9746262558",
    isHead: false,
    generation: 3,
    parentId: "najuma",
    children: [],
    branch: "Najuma PM & Dr CV Abdulla Kutty",
  },
  {
    id: "aslam",
    name: "Aslam Abdullakutty",
    profession: "App Developer",
    qualification: "BA",
    contact: "0091 9995899402",
    isHead: false,
    generation: 3,
    parentId: "najuma",
    children: [],
    branch: "Najuma PM & Dr CV Abdulla Kutty",
  },
  {
    id: "abbas-nazir",
    name: "Mohammed Abbas Nazir",
    profession: "Business",
    qualification: "B.Eng",
    contact: "00971 55 9484716",
    isHead: false,
    generation: 3,
    parentId: "nazir",
    children: [],
    branch: "PM Nazir & Shainas Alamana",
  },
  {
    id: "aysha-nazir",
    name: "Aysha Nazir",
    profession: "Strategy and Policy Consultant",
    qualification: "BSc Economics & M.S in DEDP",
    contact: "00971 50 9382699",
    isHead: false,
    generation: 3,
    parentId: "nazir",
    children: [],
    branch: "PM Nazir & Shainas Alamana",
  },
  {
    id: "adeeb",
    name: "Adeeb Abdul Majeed",
    profession: "Project Manager",
    qualification: "B.Tech, PMP",
    contact: "00971 56 9064860",
    isHead: false,
    generation: 3,
    parentId: "naseema",
    children: [],
    branch: "Naseema P. M & Abdul Majeed N.P",
  },
  {
    id: "farhana",
    name: "Dr Farhana Zakir",
    profession: "Student",
    qualification: "B.Tech, M.Tech, PhD",
    contact: "0044 7553795330",
    isHead: false,
    generation: 3,
    parentId: "naseema",
    children: [],
    branch: "Naseema P. M & Abdul Majeed N.P",
  },
  {
    id: "adheela",
    name: "Adv. Adheela Nowrin",
    profession: "Lawyer (Junior Advocate at High Court Of Kerala)",
    qualification: "BA, LL.B & LL.M",
    contact: "0091 7558944646",
    isHead: false,
    generation: 3,
    parentId: "naseema",
    children: [],
    branch: "Naseema P. M & Abdul Majeed N.P",
  },
  {
    id: "salman",
    name: "Salman Salim",
    profession: "Sales Representative",
    qualification: "BCA",
    contact: "00971 8891690013",
    isHead: false,
    generation: 3,
    parentId: "najeeba",
    children: [],
    branch: "Najeeba PM & Mohammed Salim K.H",
  },
  {
    id: "shehzad",
    name: "Shehzad Mehar",
    profession: "Student",
    qualification: "MA, BEd",
    contact: "0091 9633131204",
    isHead: false,
    generation: 3,
    parentId: "najeeba",
    children: [],
    branch: "Najeeba PM & Mohammed Salim K.H",
  },
  {
    id: "zaahir",
    name: "Zaahir Hydrose Salim",
    profession: "Engineer (Infosys)",
    qualification: "B.Tech",
    contact: "0091 9745430236",
    isHead: false,
    generation: 3,
    parentId: "najeeba",
    children: [],
    branch: "Najeeba PM & Mohammed Salim K.H",
  },
  {
    id: "zayan",
    name: "Zayan Afdal",
    isHead: false,
    generation: 4,
    parentId: "afdal",
    children: [],
    branch: "Najuma PM & Dr CV Abdulla Kutty",
  },
  {
    id: "razan",
    name: "Razan Afdal",
    isHead: false,
    generation: 4,
    parentId: "afdal",
    children: [],
    branch: "Najuma PM & Dr CV Abdulla Kutty",
  },

  // Family 2: A T kunjupathumma & P.K Athakutty - COMPLETE
  {
    id: "head-2",
    name: "A T kunjupathumma",
    isHead: true,
    generation: 1,
    spouse: "P.K Athakutty",
    children: [
      "mohammed-ali",
      "aysha-ibrahim",
      "kadeeja-aboobacker",
      "moinudheen",
      "safiya-at",
      "sainaba-at",
      "at-ashraf",
      "ramla-jaleel",
      "at-jamaludheen-late",
      "haseena-basheer",
      "thajunnisa-basheer",
    ],
    branch: "A T kunjupathumma & P.K Athakutty",
    isDeceased: true,
  },
  {
    id: "head-2-spouse",
    name: "P.K Athakutty",
    isHead: false,
    generation: 1,
    spouse: "A T kunjupathumma",
    children: [
      "mohammed-ali",
      "aysha-ibrahim",
      "kadeeja-aboobacker",
      "moinudheen",
      "safiya-at",
      "sainaba-at",
      "at-ashraf",
      "ramla-jaleel",
      "at-jamaludheen-late",
      "haseena-basheer",
      "thajunnisa-basheer",
    ],
    branch: "A T kunjupathumma & P.K Athakutty",
    isDeceased: true,
  },
  {
    id: "mohammed-ali",
    name: "A T Mohammed Ali",
    profession: "Business",
    qualification: "BSc",
    contact: "0091 9847256752",
    isHead: false,
    generation: 2,
    parentId: "head-2",
    spouse: "Valiyapurayil Mahin Ayshabi",
    children: ["sangeetha", "sanoj", "sanuja"],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "mohammed-ali-spouse",
    name: "Valiyapurayil Mahin Ayshabi",
    profession: "Homemaker",
    qualification: "Bachelor of Arts",
    contact: "0091 9645892011",
    isHead: false,
    generation: 2,
    parentId: "head-2",
    spouse: "A T Mohammed Ali",
    children: ["sangeetha", "sanoj", "sanuja"],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "sangeetha",
    name: "Sangeetha Karayil Mohammed Ali",
    profession: "Homemaker",
    qualification: "Bachelor of Arts",
    contact: "00968 91023993",
    isHead: false,
    generation: 3,
    parentId: "mohammed-ali",
    spouse: "Fazlin Anam",
    children: ["janainah"],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "fazlin",
    name: "Fazlin Anam",
    profession: "Lawyer",
    qualification: "Bachelor of Arts, Legum Baccalaureus",
    contact: "00968 91011433",
    isHead: false,
    generation: 3,
    parentId: "mohammed-ali",
    spouse: "Sangeetha Karayil Mohammed Ali",
    children: ["janainah"],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "sanoj",
    name: "Dr. Sanoj Karayil Mohammad Ali",
    profession: "Doctor",
    qualification: "MBBS, MD, FRACP, CPHQ",
    contact: "00974 3308396",
    isHead: false,
    generation: 3,
    parentId: "mohammed-ali",
    spouse: "Manaal Kalayam Kulath",
    children: ["zahra", "izaan"],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "manaal",
    name: "Manaal Kalayam Kulath",
    profession: "Engineer",
    qualification: "BE (Electronics & Communications)",
    contact: "00975 66411571",
    isHead: false,
    generation: 3,
    parentId: "mohammed-ali",
    spouse: "Dr. Sanoj Karayil Mohammad Ali",
    children: ["zahra", "izaan"],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "sanuja",
    name: "Sanuja Karayil Mohammad Ali",
    profession: "Not Working",
    qualification: "M.A.Sociology",
    contact: "0049 15126256949",
    isHead: false,
    generation: 3,
    parentId: "mohammed-ali",
    spouse: "Rizvin Azad (Richu)",
    children: ["samar"],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "rizvin",
    name: "Rizvin Azad (Richu)",
    profession: "IT Executive",
    qualification: "M.S. Engineering",
    contact: "0049 1605137421",
    isHead: false,
    generation: 3,
    parentId: "mohammed-ali",
    spouse: "Sanuja Karayil Mohammad Ali",
    children: ["samar"],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "janainah",
    name: "Janainah Fazlin Anam",
    profession: "Sports Editor",
    qualification: "Bachelor of Arts",
    isHead: false,
    generation: 4,
    parentId: "sangeetha",
    children: [],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "zahra",
    name: "Zahra Sanoj",
    profession: "Student",
    qualification: "Year 12",
    contact: "00974 33040940",
    isHead: false,
    generation: 4,
    parentId: "sanoj",
    children: [],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "izaan",
    name: "Izaan Sanoj",
    profession: "Student",
    qualification: "Year 7",
    isHead: false,
    generation: 4,
    parentId: "sanoj",
    children: [],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },
  {
    id: "samar",
    name: "Samar Ali Azad",
    profession: "Student",
    qualification: "Grade 6",
    isHead: false,
    generation: 4,
    parentId: "sanuja",
    children: [],
    branch: "A T Mohammed Ali & V.M Ayshabi",
  },

  // Family 3: A T Pathavu & Veetiparambil Avvutty - COMPLETE
  {
    id: "head-3",
    name: "A T Pathavu",
    isHead: true,
    generation: 1,
    spouse: "Veetiparambil Avvutty",
    children: [
      "abdul-rahman-at",
      "muhammed-unni-at",
      "at-moinudheen-pathavu",
      "at-suharabi-pathavu",
      "maharunnisa-ali",
    ],
    branch: "A T Pathavu & Veetiparambil Avvutty",
    isDeceased: true,
  },
  {
    id: "head-3-spouse",
    name: "Veetiparambil Avvutty",
    isHead: false,
    generation: 1,
    spouse: "A T Pathavu",
    children: [
      "abdul-rahman-at",
      "muhammed-unni-at",
      "at-moinudheen-pathavu",
      "at-suharabi-pathavu",
      "maharunnisa-ali",
    ],
    branch: "A T Pathavu & Veetiparambil Avvutty",
    isDeceased: true,
  },
  {
    id: "abdul-rahman-at",
    name: "Abdul Rahman AT",
    profession: "Retired UAE Armed Force",
    contact: "0091 9746295768",
    isHead: false,
    generation: 2,
    parentId: "head-3",
    spouse: "Asma Abdul Rahman",
    children: ["sajith-at", "sadna-anis", "thamanna-abdul-rahman"],
    branch: "Abdul Rahman AT & Asma Abdul Rahman",
  },
  {
    id: "asma-abdul-rahman",
    name: "Asma Abdul Rahman",
    profession: "Homemaker",
    qualification: "SSLC",
    contact: "0091 9544377883",
    isHead: false,
    generation: 2,
    parentId: "head-3",
    spouse: "Abdul Rahman AT",
    children: ["sajith-at", "sadna-anis", "thamanna-abdul-rahman"],
    branch: "Abdul Rahman AT & Asma Abdul Rahman",
  },
  {
    id: "sajith-at",
    name: "Sajith AT",
    profession: "Head of Reservation Dept, Greyline",
    qualification: "BBA, IATA, MBA",
    contact: "00968 93000381",
    isHead: false,
    generation: 3,
    parentId: "abdul-rahman-at",
    spouse: "Ansa Sajith",
    children: ["sheza-sajith", "ayman-sajith"],
    branch: "Abdul Rahman AT & Asma Abdul Rahman",
  },
  {
    id: "ansa-sajith",
    name: "Ansa Sajith",
    profession: "Homemaker",
    qualification: "BSc Computer Science",
    contact: "0091 9947483913",
    isHead: false,
    generation: 3,
    parentId: "abdul-rahman-at",
    spouse: "Sajith AT",
    children: ["sheza-sajith", "ayman-sajith"],
    branch: "Abdul Rahman AT & Asma Abdul Rahman",
  },
  {
    id: "sheza-sajith",
    name: "Sheza Sajith",
    profession: "Student",
    qualification: "Grade 6",
    isHead: false,
    generation: 4,
    parentId: "sajith-at",
    children: [],
    branch: "Abdul Rahman AT & Asma Abdul Rahman",
  },
  {
    id: "ayman-sajith",
    name: "Ayman Sajith",
    profession: "Student",
    qualification: "Grade 4",
    isHead: false,
    generation: 4,
    parentId: "sajith-at",
    children: [],
    branch: "Abdul Rahman AT & Asma Abdul Rahman",
  },

  // Family 4: A T Nafeesakutty & M.A Bappu Moulavi - COMPLETE
  {
    id: "head-4",
    name: "A T Nafeesakutty",
    isHead: true,
    generation: 1,
    spouse: "M.A Bappu Moulavi",
    children: ["abdul-salam", "at-jabir", "saeed", "najeeb-at", "at-minneth", "mohammed-sageer-at"],
    branch: "A T Nafeesakutty & M.A Bappu Moulavi",
  },
  {
    id: "head-4-spouse",
    name: "M.A Bappu Moulavi",
    isHead: false,
    generation: 1,
    spouse: "A T Nafeesakutty",
    children: ["abdul-salam", "at-jabir", "saeed", "najeeb-at", "at-minneth", "mohammed-sageer-at"],
    branch: "A T Nafeesakutty & M.A Bappu Moulavi",
    isDeceased: true,
  },
  {
    id: "abdul-salam",
    name: "Abdul Salam",
    profession: "Accountant",
    qualification: "PDC",
    contact: "00974 66989496",
    isHead: false,
    generation: 2,
    parentId: "head-4",
    spouse: "Sakeena",
    children: ["basil-karakkat", "shifa-karakkat", "basim-karakkat"],
    branch: "Abdul Salam & Sakeena",
  },
  {
    id: "sakeena-abdul-salam",
    name: "Sakeena",
    profession: "Homemaker",
    qualification: "School",
    contact: "00974 33660870",
    isHead: false,
    generation: 2,
    parentId: "head-4",
    spouse: "Abdul Salam",
    children: ["basil-karakkat", "shifa-karakkat", "basim-karakkat"],
    branch: "Abdul Salam & Sakeena",
  },
  {
    id: "basil-karakkat",
    name: "Basil Karakkat",
    profession: "Accountant",
    qualification: "ACCA",
    contact: "00974 77011998",
    isHead: false,
    generation: 3,
    parentId: "abdul-salam",
    spouse: "Nejila Basil",
    children: ["omar-basil"],
    branch: "Abdul Salam & Sakeena",
  },
  {
    id: "nejila-basil",
    name: "Nejila Basil",
    profession: "Homemaker",
    qualification: "Graduate",
    contact: "00974 77574712",
    isHead: false,
    generation: 3,
    parentId: "abdul-salam",
    spouse: "Basil Karakkat",
    children: ["omar-basil"],
    branch: "Abdul Salam & Sakeena",
  },
  {
    id: "omar-basil",
    name: "Omar Basil",
    profession: "Toddler",
    qualification: "Toddler",
    isHead: false,
    generation: 4,
    parentId: "basil-karakkat",
    children: [],
    branch: "Abdul Salam & Sakeena",
  },

  // Family 5: A.T AliKunji & P.K Kunhipathunni - COMPLETE
  {
    id: "head-5",
    name: "A.T AliKunji",
    isHead: true,
    generation: 1,
    spouse: "P.K Kunhipathunni",
    children: ["nisha-basheer", "naina-imthias", "najna-haris"],
    branch: "A.T AliKunji & P.K Kunhipathunni",
    isDeceased: true,
  },
  {
    id: "head-5-spouse",
    name: "P.K Kunhipathunni",
    isHead: false,
    generation: 1,
    spouse: "A.T AliKunji",
    children: ["nisha-basheer", "naina-imthias", "najna-haris"],
    branch: "A.T AliKunji & P.K Kunhipathunni",
    contact: "0091 9744380034",
  },
  {
    id: "nisha-basheer",
    name: "Nisha Basheer",
    profession: "Homemaker",
    contact: "00971 552852566",
    isHead: false,
    generation: 2,
    parentId: "head-5",
    spouse: "K.V Mohammed Basheer",
    children: ["bindhiya-basheer", "zahid-basheer"],
    branch: "Nisha Basheer & K.V Mohammed Basheer",
  },
  {
    id: "kv-mohammed-basheer",
    name: "K.V Mohammed Basheer",
    profession: "Logistics Manager",
    qualification: "BCom",
    contact: "00971 507892337",
    isHead: false,
    generation: 2,
    parentId: "head-5",
    spouse: "Nisha Basheer",
    children: ["bindhiya-basheer", "zahid-basheer"],
    branch: "Nisha Basheer & K.V Mohammed Basheer",
  },
  {
    id: "bindhiya-basheer",
    name: "Bindhiya Basheer",
    profession: "Senior Executive Secretary",
    qualification: "MBA - HR",
    contact: "00974 60088233",
    isHead: false,
    generation: 3,
    parentId: "nisha-basheer",
    spouse: "Suhail Hamza",
    children: ["azam-suhail", "aman-suhail", "zoha-suhail"],
    branch: "Nisha Basheer & K.V Mohammed Basheer",
  },
  {
    id: "suhail-hamza",
    name: "Suhail Hamza",
    profession: "Logistics Business Development Manager",
    qualification: "MBA - International Business",
    contact: "00974 66605676",
    isHead: false,
    generation: 3,
    parentId: "nisha-basheer",
    spouse: "Bindhiya Basheer",
    children: ["azam-suhail", "aman-suhail", "zoha-suhail"],
    branch: "Nisha Basheer & K.V Mohammed Basheer",
  },
  {
    id: "azam-suhail",
    name: "Azam Suhail",
    profession: "Student",
    qualification: "Grade 10",
    isHead: false,
    generation: 4,
    parentId: "bindhiya-basheer",
    children: [],
    branch: "Nisha Basheer & K.V Mohammed Basheer",
  },
  {
    id: "aman-suhail",
    name: "Aman Suhail",
    profession: "Student",
    qualification: "Grade 9",
    isHead: false,
    generation: 4,
    parentId: "bindhiya-basheer",
    children: [],
    branch: "Nisha Basheer & K.V Mohammed Basheer",
  },
  {
    id: "zoha-suhail",
    name: "Zoha Suhail",
    profession: "Student",
    qualification: "Grade 7",
    isHead: false,
    generation: 4,
    parentId: "bindhiya-basheer",
    children: [],
    branch: "Nisha Basheer & K.V Mohammed Basheer",
  },

  // Family 6: A.T Kunjaisu & R.V Mohammed Haji - COMPLETE
  {
    id: "head-6",
    name: "A.T Kunjaisu",
    isHead: true,
    generation: 1,
    spouse: "R.V Mohammed Haji",
    children: ["at-suharabi-kunjaisu", "at-basheer", "at-imthias", "haseena-at-kunjaisu", "illyas-at", "dr-ihsan-at"],
    branch: "A.T Kunjaisu & R.V Mohammed Haji",
    isDeceased: true,
  },
  {
    id: "head-6-spouse",
    name: "R.V Mohammed Haji",
    isHead: false,
    generation: 1,
    spouse: "A.T Kunjaisu",
    children: ["at-suharabi-kunjaisu", "at-basheer", "at-imthias", "haseena-at-kunjaisu", "illyas-at", "dr-ihsan-at"],
    branch: "A.T Kunjaisu & R.V Mohammed Haji",
    isDeceased: true,
  },
  {
    id: "at-suharabi-kunjaisu",
    name: "A T Suharabi",
    profession: "Homemaker",
    qualification: "Grade 10",
    contact: "919847519004, 971509547550",
    isHead: false,
    generation: 2,
    parentId: "head-6",
    spouse: "Muzammilu Kombanezhath Beeran",
    children: ["raheem-km", "rakeeb-km", "fathima-abdul-raoof"],
    branch: "A T Suharabi & Muzammilu Kombanezhath Beeran",
  },
  {
    id: "muzammilu-kombanezhath-beeran",
    name: "Muzammilu Kombanezhath Beeran",
    isHead: false,
    generation: 2,
    parentId: "head-6",
    spouse: "A T Suharabi",
    children: ["raheem-km", "rakeeb-km", "fathima-abdul-raoof"],
    branch: "A T Suharabi & Muzammilu Kombanezhath Beeran",
    isDeceased: true,
  },

  // Family 7: A.T Aminakutty & A.M Bavu - COMPLETE
  {
    id: "head-7",
    name: "A.T Aminakutty",
    isHead: true,
    generation: 1,
    spouse: "A.M Bavu",
    children: ["jameela-at", "sharafudheen-at", "sabira-at", "sakeena-at-aminakutty", "rabiya-at"],
    branch: "A.T Aminakutty & A.M Bavu",
    isDeceased: true,
  },
  {
    id: "head-7-spouse",
    name: "A.M Bavu",
    isHead: false,
    generation: 1,
    spouse: "A.T Aminakutty",
    children: ["jameela-at", "sharafudheen-at", "sabira-at", "sakeena-at-aminakutty", "rabiya-at"],
    branch: "A.T Aminakutty & A.M Bavu",
    isDeceased: true,
  },
  {
    id: "jameela-at",
    name: "Jameela A.T",
    profession: "Homemaker",
    contact: "0091 9562054698",
    isHead: false,
    generation: 2,
    parentId: "head-7",
    spouse: "Mohamed Ali M.K",
    children: ["miraj-mohamed", "manoj-mohamed", "rahmath-mm"],
    branch: "Jameela A.T & Mohamed Ali M.K",
  },
  {
    id: "mohamed-ali-mk",
    name: "Mohamed Ali M.K",
    profession: "Business",
    contact: "0091 9961519872",
    isHead: false,
    generation: 2,
    parentId: "head-7",
    spouse: "Jameela A.T",
    children: ["miraj-mohamed", "manoj-mohamed", "rahmath-mm"],
    branch: "Jameela A.T & Mohamed Ali M.K",
  },

  // Family 8: A T Aboobacker & Rasiya .P.N - COMPLETE
  {
    id: "head-8",
    name: "A T Aboobacker",
    isHead: true,
    generation: 1,
    spouse: "Rasiya .P.N",
    children: ["rajeesh-pn", "dr-raseem-pn", "rayees-pn", "rafeeque-pn"],
    branch: "A T Aboobacker & Rasiya .P.N",
    isDeceased: true,
  },
  {
    id: "head-8-spouse",
    name: "Rasiya .P.N",
    isHead: false,
    generation: 1,
    spouse: "A T Aboobacker",
    children: ["rajeesh-pn", "dr-raseem-pn", "rayees-pn", "rafeeque-pn"],
    branch: "A T Aboobacker & Rasiya .P.N",
  },
  {
    id: "rajeesh-pn",
    name: "Rajeesh.P.N",
    profession: "Business",
    qualification: "MSc",
    isHead: false,
    generation: 2,
    parentId: "head-8",
    spouse: "Rasmi.A",
    children: ["riza-pn", "mohamed-razan-pn"],
    branch: "Rajeesh.P.N & Rasmi.A",
  },
  {
    id: "rasmi-a",
    name: "Rasmi.A",
    profession: "Professor",
    qualification: "PhD",
    isHead: false,
    generation: 2,
    parentId: "head-8",
    spouse: "Rajeesh.P.N",
    children: ["riza-pn", "mohamed-razan-pn"],
    branch: "Rajeesh.P.N & Rasmi.A",
  },

  // Family 9: A.T Zainba & Abdul Kadar - COMPLETE
  {
    id: "head-9",
    name: "A.T Zainba",
    isHead: true,
    generation: 1,
    spouse: "Abdul Kadar",
    children: ["at-jamaludheen-zainba", "at-rasheed", "at-kabeer", "khyrunnisa-mohamed", "at-mujeeb"],
    branch: "A.T Zainba & Abdul Kadar",
  },
  {
    id: "head-9-spouse",
    name: "Abdul Kadar",
    isHead: false,
    generation: 1,
    spouse: "A.T Zainba",
    children: ["at-jamaludheen-zainba", "at-rasheed", "at-kabeer", "khyrunnisa-mohamed", "at-mujeeb"],
    branch: "A.T Zainba & Abdul Kadar",
  },
  {
    id: "at-jamaludheen-zainba",
    name: "A.T Jamaludheen",
    profession: "Business",
    contact: "00971 50 2140450",
    isHead: false,
    generation: 2,
    parentId: "head-9",
    spouse: "A.T Shajitha",
    children: ["sajjadh-jamal", "hiba-jamaludheen", "adhnan-jamal"],
    branch: "A.T Jamaludheen & A.T Shajitha",
  },
  {
    id: "at-shajitha",
    name: "A.T Shajitha",
    profession: "Homemaker",
    contact: "0091 8086878352",
    isHead: false,
    generation: 2,
    parentId: "head-9",
    spouse: "A.T Jamaludheen",
    children: ["sajjadh-jamal", "hiba-jamaludheen", "adhnan-jamal"],
    branch: "A.T Jamaludheen & A.T Shajitha",
  },

  // Family 10: A T Ibrahimkutty & Zuhara Ibrahim - COMPLETE
  {
    id: "head-10",
    name: "A T Ibrahimkutty",
    profession: "Farmer (Gulf Retired)",
    qualification: "SSLC",
    contact: "0091 9449671555",
    isHead: true,
    generation: 1,
    spouse: "Zuhara Ibrahim",
    children: ["dr-najeeb-ibrahim", "adv-naeem-ibrahim", "nadiya-ibrahim", "nabeel-ibrahim", "nasia-ibrahim"],
    branch: "A T Ibrahimkutty & Zuhara Ibrahim",
  },
  {
    id: "head-10-spouse",
    name: "Zuhara Ibrahim",
    profession: "Homemaker",
    qualification: "SSLC",
    contact: "0091 9207916624",
    isHead: false,
    generation: 1,
    spouse: "A T Ibrahimkutty",
    children: ["dr-najeeb-ibrahim", "adv-naeem-ibrahim", "nadiya-ibrahim", "nabeel-ibrahim", "nasia-ibrahim"],
    branch: "A T Ibrahimkutty & Zuhara Ibrahim",
  },
  {
    id: "dr-najeeb-ibrahim",
    name: "Dr. Najeeb Ibrahim",
    profession: "Doctor",
    qualification: "BDS",
    contact: "00968 98230488",
    isHead: false,
    generation: 2,
    parentId: "head-10",
    spouse: "Dr. Sapna Najeeb",
    children: ["haadi-najeeb", "nazli-najeeb"],
    branch: "Dr. Najeeb Ibrahim & Dr. Sapna Najeeb",
  },
  {
    id: "dr-sapna-najeeb",
    name: "Dr. Sapna Najeeb",
    profession: "Doctor",
    qualification: "BDS",
    contact: "0091 7034961552",
    isHead: false,
    generation: 2,
    parentId: "head-10",
    spouse: "Dr. Najeeb Ibrahim",
    children: ["haadi-najeeb", "nazli-najeeb"],
    branch: "Dr. Najeeb Ibrahim & Dr. Sapna Najeeb",
  },
  {
    id: "haadi-najeeb",
    name: "Haadi Najeeb",
    profession: "Student",
    qualification: "Grade 12 (Commerce/Computer)",
    contact: "0091 9846531432",
    isHead: false,
    generation: 3,
    parentId: "dr-najeeb-ibrahim",
    children: [],
    branch: "Dr. Najeeb Ibrahim & Dr. Sapna Najeeb",
  },
  {
    id: "nazli-najeeb",
    name: "Nazli Najeeb Ibrahim",
    profession: "Student",
    qualification: "Grade 8",
    isHead: false,
    generation: 3,
    parentId: "dr-najeeb-ibrahim",
    children: [],
    branch: "Dr. Najeeb Ibrahim & Dr. Sapna Najeeb",
  },
]

// Initialize the family data when the script loads
document.addEventListener("DOMContentLoaded", () => {
  // Set the global family data
  window.familyData = familyData
})
